---
# Main playbook
- name: Install Pi
  hosts: pi
  remote_user: root

  roles:
        - { role: common, tags: [ 'common' ] }
        - { role: mopidy, tags: [ 'mopidy' ] }
        - { role: web, tags: [ 'web' ] }
